#(オプション) Googleアナリティクスを使用している場合は、Googleアナリティクスを設定します。
#必ず設定ファイルの一番上に設定してください。
googleAnalytics = "UA-127138082-1"

# (オプション) Disqus のショートネームを指定すると、すべてのページでコメントが有効になります。
#disqusShortname = "my-site"

# (オプション) ファイル名に大文字を使用する場合はtrueに設定します。
#disablePathToLower = true

# (オプション) これを true にすると、'doc' タイプのページで 'Last Modified by' の日付と git author の情報を有効にします。
#enableGitInfo = true

# (オプション) テーマは文書化を目的としたものなので、タクソノミーは表示されません。
# 以下の設定で関連ファイルを削除することができます
#disableKinds = ['taxonomy', 'taxonomyTerm']

#Hugo でデフォルト設定では、日本語のサマリーが長くなってしまうことがあります。日本語の文章を短いサマリーで表示できるようにするには、設定ファイル (config.toml 等) に hasCJKLanguage を追加し true に設定します。
hasCJKLanguage = true

baseURL = "https://dolphilia.com/"
languageCode = "ja"
title = "dolphilia.com"
theme = "book"

[params]
  # (オプション, デフォルトのlight) 色のテーマを設定します: 明るい,暗い,または自動.
  # テーマ'auto'はブラウザ/OSの環境設定に基づいて, 明暗のモードを切り替えます.
  BookTheme = 'auto'

  # (オプション, デフォルトはtrue) ページの右側に表示される目次を制御します.
  # 開始レベルと終了レベルは, markup.tableOfContentsの設定で制御できます.
  # このパラメータは, フロントマターのページごとに指定することもできます.
  BookToC = true
  
  # (オプシ ョ ナル、 デフ ォル ト では none) 本のロ ゴのパスを設定します。ロゴが/static/logo.pngの場合、パスは「logo.png」になります。
  #BookLogo = 'logo.png'
  
  # (オプション、デフォルトは none) リーフバンドルをサイドメニューとしてレンダリングするように設定します。指定されていない場合は、ファイル構造と重みが使用されます。
  #BookMenuBundle = '/menu'
  
  # (オプション、デフォルトの docs) メニューとしてレンダリングするコンテンツのセクションを指定します。
  # すべてのセクションをメニューに表示するには "*"を指定することもできます.
  #BookSection = 'docs'
  
  # ソースリポジトリの場所を設定します.
  # '最終更新日'と'このページを編集する'リンクに使用されます.
  #BookRepo = 'https://github.com/dolphilia/dolphilia.com'
  
  # 'doc'ページタイプの'このページを編集する'リンクを有効にします.
  # デフォルトでは無効化されています. 有効にするにはコメントを外します. パラメータ 'BookRepo' が必要です.
  # パスはサイトのディレクトリを指している必要があります.
  #BookEditPath = 'edit/master/exampleSite'
  
  # (Optional, default January 2, 2006) Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = '2006-01-02'
  
  # (オプション、デフォルトはtrue) flexsearchで検索機能を有効にします。
  # インデックスはオンザフライで作成されるため, ウェブサイトの速度が低下する可能性があります.
  # インデックスの設定は, 言語ごとにi18nフォルダで調整することができます.
  BookSearch = true
  
  # (オプション、デフォルトはtrue) ページのコメントテンプレートを有効にする
  # デフォルトでは partials/docs/comments.html には Disqus テンプレートが含まれています．
  # https://gohugo.io/content-management/comments/#configure-disqus を参照してください。
  # ページフロントマッターの同じパラメータで上書きすることができます．
  BookComments = true
  
  # これは実験的な機能なので、いつでも削除・変更できるかもしれません。
  # (オプション、実験的、デフォルトはfalse) # (オプション、実験的、デフォルトはfalse) markdownページのポータブルリンクとリンクチェックを有効にします。
  # ポータブルリンクはテキストエディタで動作し、{{< relref >}}ショートコードなしでマークダウンを書くことができます。
  # マークダウンで参照されているページが存在しない場合、テーマは警告を表示します.
  #BookPortableLinks = true
  
  # これは実験的な機能なので、いつでも削除・変更できるかもしれません。
  # (オプション, experimental, default false) 訪問したページやリソースをキャッシュしてオフラインで使用するサービスワーカーを有効にします。
  #BookServiceWorker = true
  
  #------ ページについて
  
  # 設定されたセクション以外のページをレンダリングしたい場合や、'docs'以外のセクションをレンダリングする場合は、型を'docs'に設定します。
#type = 'docs'

# ファイルツリーメニューの項目を再配置するためにページの重みを設定する (BookMenuBundleが設定されていない場合)
#weight = 10

# (オプション) ファイルツリーメニューでページをフラットセクションとしてマークするために true を設定します (BookMenuBundle が設定されていない場合)。
#bookFlatSection = false

# (オプション) そのレベルで入れ子になっているセクションやページを隠すように設定します。ファイルツリーメニューモードでのみ動作します。
#bookCollapseSection = true

# (オプション) サイドメニューからページやセクションを非表示にするかどうかを設定します(BookMenuBundleが設定されていない場合)。
#bookHidden = false

# (オプション) 'false' を設定すると、ページから ToC を隠すことができます。
#bookToC = true

# (オプション) サイトでBookCommentsを有効にしている場合は、特定のページに対して無効にすることができます。
#bookComments = true

# (オプション) 検索インデックスからページを除外するには'false'を設定します。
bookSearchExclude = true